'use strict';

const METRICS = [
  { key: 'battery_level', label: 'State of charge (display)', group: 'charge_state', path: 'charge_state.battery_level', type: 'number', unit: '%', scope: 'vehicle_device_data' },
  { key: 'usable_battery_level', label: 'State of charge (usable)', group: 'charge_state', path: 'charge_state.usable_battery_level', type: 'number', unit: '%', scope: 'vehicle_device_data' },
  { key: 'battery_range', label: 'Battery range (rated)', group: 'charge_state', path: 'charge_state.battery_range', type: 'number', unit: 'mi', scope: 'vehicle_device_data' },
  { key: 'est_battery_range', label: 'Battery range (estimated)', group: 'charge_state', path: 'charge_state.est_battery_range', type: 'number', unit: 'mi', scope: 'vehicle_device_data' },
  { key: 'ideal_battery_range', label: 'Battery range (ideal)', group: 'charge_state', path: 'charge_state.ideal_battery_range', type: 'number', unit: 'mi', scope: 'vehicle_device_data' },
  { key: 'charging_state', label: 'Charging state', group: 'charge_state', path: 'charge_state.charging_state', type: 'string', scope: 'vehicle_device_data' },
  { key: 'charge_enable_request', label: 'Charging enabled', group: 'charge_state', path: 'charge_state.charge_enable_request', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'charge_energy_added', label: 'Energy added this session', group: 'charge_state', path: 'charge_state.charge_energy_added', type: 'number', unit: 'kWh', scope: 'vehicle_device_data' },
  { key: 'charge_miles_added_rated', label: 'Rated miles added this session', group: 'charge_state', path: 'charge_state.charge_miles_added_rated', type: 'number', unit: 'mi', scope: 'vehicle_device_data' },
  { key: 'charge_miles_added_ideal', label: 'Ideal miles added this session', group: 'charge_state', path: 'charge_state.charge_miles_added_ideal', type: 'number', unit: 'mi', scope: 'vehicle_device_data' },
  { key: 'charge_rate', label: 'Charge rate', group: 'charge_state', path: 'charge_state.charge_rate', type: 'number', unit: 'mi/hr', scope: 'vehicle_device_data' },
  { key: 'charge_limit_soc', label: 'Charge limit', group: 'charge_state', path: 'charge_state.charge_limit_soc', type: 'number', unit: '%', scope: 'vehicle_device_data' },
  { key: 'charge_limit_soc_std', label: 'Charge limit (standard)', group: 'charge_state', path: 'charge_state.charge_limit_soc_std', type: 'number', unit: '%', scope: 'vehicle_device_data' },
  { key: 'charge_limit_soc_min', label: 'Charge limit (minimum settable)', group: 'charge_state', path: 'charge_state.charge_limit_soc_min', type: 'number', unit: '%', scope: 'vehicle_device_data' },
  { key: 'charge_limit_soc_max', label: 'Charge limit (maximum settable)', group: 'charge_state', path: 'charge_state.charge_limit_soc_max', type: 'number', unit: '%', scope: 'vehicle_device_data' },
  { key: 'charge_amps', label: 'Charge current setting', group: 'charge_state', path: 'charge_state.charge_amps', type: 'number', unit: 'A', scope: 'vehicle_device_data' },
  { key: 'charge_current_request', label: 'Charge current request', group: 'charge_state', path: 'charge_state.charge_current_request', type: 'number', unit: 'A', scope: 'vehicle_device_data' },
  { key: 'charge_current_request_max', label: 'Charge current request (max)', group: 'charge_state', path: 'charge_state.charge_current_request_max', type: 'number', unit: 'A', scope: 'vehicle_device_data' },
  { key: 'charger_actual_current', label: 'Charger actual current', group: 'charge_state', path: 'charge_state.charger_actual_current', type: 'number', unit: 'A', scope: 'vehicle_device_data' },
  { key: 'charger_pilot_current', label: 'Charger pilot current', group: 'charge_state', path: 'charge_state.charger_pilot_current', type: 'number', unit: 'A', scope: 'vehicle_device_data' },
  { key: 'charger_power', label: 'Charger power', group: 'charge_state', path: 'charge_state.charger_power', type: 'number', unit: 'kW', scope: 'vehicle_device_data' },
  { key: 'charger_voltage', label: 'Charger voltage', group: 'charge_state', path: 'charge_state.charger_voltage', type: 'number', unit: 'V', scope: 'vehicle_device_data' },
  { key: 'charger_phases', label: 'Charger phases', group: 'charge_state', path: 'charge_state.charger_phases', type: 'number', scope: 'vehicle_device_data' },
  { key: 'minutes_to_full_charge', label: 'Minutes to full charge', group: 'charge_state', path: 'charge_state.minutes_to_full_charge', type: 'number', unit: 'min', scope: 'vehicle_device_data' },
  { key: 'time_to_full_charge', label: 'Hours to full charge', group: 'charge_state', path: 'charge_state.time_to_full_charge', type: 'number', unit: 'hr', scope: 'vehicle_device_data' },
  { key: 'battery_heater_on', label: 'Battery heater on', group: 'charge_state', path: 'charge_state.battery_heater_on', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'charge_port_door_open', label: 'Charge port door open', group: 'charge_state', path: 'charge_state.charge_port_door_open', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'charge_port_latch', label: 'Charge port latch', group: 'charge_state', path: 'charge_state.charge_port_latch', type: 'string', scope: 'vehicle_device_data' },
  { key: 'charge_port_color', label: 'Charge port light color', group: 'charge_state', path: 'charge_state.charge_port_color', type: 'string', scope: 'vehicle_device_data' },
  { key: 'conn_charge_cable', label: 'Connected cable type', group: 'charge_state', path: 'charge_state.conn_charge_cable', type: 'string', scope: 'vehicle_device_data' },
  { key: 'fast_charger_present', label: 'Fast charger present', group: 'charge_state', path: 'charge_state.fast_charger_present', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'fast_charger_brand', label: 'Fast charger brand', group: 'charge_state', path: 'charge_state.fast_charger_brand', type: 'string', scope: 'vehicle_device_data' },
  { key: 'fast_charger_type', label: 'Fast charger type', group: 'charge_state', path: 'charge_state.fast_charger_type', type: 'string', scope: 'vehicle_device_data' },
  { key: 'trip_charging', label: 'Trip charging', group: 'charge_state', path: 'charge_state.trip_charging', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'supercharger_session_trip_planner', label: 'Supercharger session via trip planner', group: 'charge_state', path: 'charge_state.supercharger_session_trip_planner', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'scheduled_charging_mode', label: 'Scheduled charging mode', group: 'charge_state', path: 'charge_state.scheduled_charging_mode', type: 'string', scope: 'vehicle_device_data' },
  { key: 'scheduled_charging_pending', label: 'Scheduled charging pending', group: 'charge_state', path: 'charge_state.scheduled_charging_pending', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'scheduled_charging_start_time', label: 'Scheduled charging start time', group: 'charge_state', path: 'charge_state.scheduled_charging_start_time', type: 'number', unit: 's', scope: 'vehicle_device_data' },
  { key: 'scheduled_charging_start_time_app', label: 'Scheduled charging start time (app)', group: 'charge_state', path: 'charge_state.scheduled_charging_start_time_app', type: 'number', unit: 'min', scope: 'vehicle_device_data' },
  { key: 'scheduled_departure_time', label: 'Scheduled departure time', group: 'charge_state', path: 'charge_state.scheduled_departure_time', type: 'number', unit: 's', scope: 'vehicle_device_data' },
  { key: 'scheduled_departure_time_minutes', label: 'Scheduled departure time (minutes)', group: 'charge_state', path: 'charge_state.scheduled_departure_time_minutes', type: 'number', unit: 'min', scope: 'vehicle_device_data' },
  { key: 'off_peak_charging_enabled', label: 'Off-peak charging enabled', group: 'charge_state', path: 'charge_state.off_peak_charging_enabled', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'off_peak_charging_times', label: 'Off-peak charging times', group: 'charge_state', path: 'charge_state.off_peak_charging_times', type: 'string', scope: 'vehicle_device_data' },
  { key: 'off_peak_hours_end_time', label: 'Off-peak hours end time', group: 'charge_state', path: 'charge_state.off_peak_hours_end_time', type: 'number', unit: 'min', scope: 'vehicle_device_data' },
  { key: 'preconditioning_enabled', label: 'Departure preconditioning enabled', group: 'charge_state', path: 'charge_state.preconditioning_enabled', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'preconditioning_times', label: 'Preconditioning times', group: 'charge_state', path: 'charge_state.preconditioning_times', type: 'string', scope: 'vehicle_device_data' },
  { key: 'charge_state_timestamp', label: 'Charge state timestamp', group: 'charge_state', path: 'charge_state.timestamp', type: 'number', unit: 'ms', scope: 'vehicle_device_data' },
  { key: 'inside_temp', label: 'Inside temperature', group: 'climate_state', path: 'climate_state.inside_temp', type: 'number', unit: 'C', scope: 'vehicle_device_data' },
  { key: 'outside_temp', label: 'Outside temperature', group: 'climate_state', path: 'climate_state.outside_temp', type: 'number', unit: 'C', scope: 'vehicle_device_data' },
  { key: 'driver_temp_setting', label: 'Driver temperature setting', group: 'climate_state', path: 'climate_state.driver_temp_setting', type: 'number', unit: 'C', scope: 'vehicle_device_data' },
  { key: 'passenger_temp_setting', label: 'Passenger temperature setting', group: 'climate_state', path: 'climate_state.passenger_temp_setting', type: 'number', unit: 'C', scope: 'vehicle_device_data' },
  { key: 'max_avail_temp', label: 'Max available temperature', group: 'climate_state', path: 'climate_state.max_avail_temp', type: 'number', unit: 'C', scope: 'vehicle_device_data' },
  { key: 'min_avail_temp', label: 'Min available temperature', group: 'climate_state', path: 'climate_state.min_avail_temp', type: 'number', unit: 'C', scope: 'vehicle_device_data' },
  { key: 'is_climate_on', label: 'Climate on', group: 'climate_state', path: 'climate_state.is_climate_on', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'is_auto_conditioning_on', label: 'Auto conditioning on', group: 'climate_state', path: 'climate_state.is_auto_conditioning_on', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'is_preconditioning', label: 'Preconditioning in progress', group: 'climate_state', path: 'climate_state.is_preconditioning', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'is_front_defroster_on', label: 'Front defroster on', group: 'climate_state', path: 'climate_state.is_front_defroster_on', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'is_rear_defroster_on', label: 'Rear defroster on', group: 'climate_state', path: 'climate_state.is_rear_defroster_on', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'defrost_mode', label: 'Defrost mode', group: 'climate_state', path: 'climate_state.defrost_mode', type: 'number', scope: 'vehicle_device_data' },
  { key: 'fan_status', label: 'Fan speed level', group: 'climate_state', path: 'climate_state.fan_status', type: 'number', scope: 'vehicle_device_data' },
  { key: 'climate_keeper_mode', label: 'Climate keeper mode', group: 'climate_state', path: 'climate_state.climate_keeper_mode', type: 'string', scope: 'vehicle_device_data' },
  { key: 'battery_heater', label: 'Battery heater active', group: 'climate_state', path: 'climate_state.battery_heater', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'bioweapon_mode', label: 'Bioweapon Defense Mode', group: 'climate_state', path: 'climate_state.bioweapon_mode', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'cabin_overheat_protection', label: 'Cabin overheat protection', group: 'climate_state', path: 'climate_state.cabin_overheat_protection', type: 'string', scope: 'vehicle_device_data' },
  { key: 'cabin_overheat_protection_actively_cooling', label: 'Cabin overheat protection cooling now', group: 'climate_state', path: 'climate_state.cabin_overheat_protection_actively_cooling', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'cop_activation_temperature', label: 'Cabin overheat protection threshold', group: 'climate_state', path: 'climate_state.cop_activation_temperature', type: 'string', scope: 'vehicle_device_data' },
  { key: 'seat_heater_left', label: 'Seat heater front left', group: 'climate_state', path: 'climate_state.seat_heater_left', type: 'number', scope: 'vehicle_device_data' },
  { key: 'seat_heater_right', label: 'Seat heater front right', group: 'climate_state', path: 'climate_state.seat_heater_right', type: 'number', scope: 'vehicle_device_data' },
  { key: 'seat_heater_rear_left', label: 'Seat heater rear left', group: 'climate_state', path: 'climate_state.seat_heater_rear_left', type: 'number', scope: 'vehicle_device_data' },
  { key: 'seat_heater_rear_center', label: 'Seat heater rear center', group: 'climate_state', path: 'climate_state.seat_heater_rear_center', type: 'number', scope: 'vehicle_device_data' },
  { key: 'seat_heater_rear_right', label: 'Seat heater rear right', group: 'climate_state', path: 'climate_state.seat_heater_rear_right', type: 'number', scope: 'vehicle_device_data' },
  { key: 'seat_heater_third_row_left', label: 'Seat heater third row left', group: 'climate_state', path: 'climate_state.seat_heater_third_row_left', type: 'number', scope: 'vehicle_device_data' },
  { key: 'seat_heater_third_row_right', label: 'Seat heater third row right', group: 'climate_state', path: 'climate_state.seat_heater_third_row_right', type: 'number', scope: 'vehicle_device_data' },
  { key: 'auto_seat_climate_left', label: 'Auto seat climate left', group: 'climate_state', path: 'climate_state.auto_seat_climate_left', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'auto_seat_climate_right', label: 'Auto seat climate right', group: 'climate_state', path: 'climate_state.auto_seat_climate_right', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'steering_wheel_heater', label: 'Steering wheel heater on', group: 'climate_state', path: 'climate_state.steering_wheel_heater', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'steering_wheel_heat_level', label: 'Steering wheel heat level', group: 'climate_state', path: 'climate_state.steering_wheel_heat_level', type: 'number', scope: 'vehicle_device_data' },
  { key: 'auto_steering_wheel_heat', label: 'Auto steering wheel heat', group: 'climate_state', path: 'climate_state.auto_steering_wheel_heat', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'side_mirror_heaters', label: 'Side mirror heaters', group: 'climate_state', path: 'climate_state.side_mirror_heaters', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'wiper_blade_heater', label: 'Wiper blade heater', group: 'climate_state', path: 'climate_state.wiper_blade_heater', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'hvac_auto_request', label: 'HVAC auto request', group: 'climate_state', path: 'climate_state.hvac_auto_request', type: 'string', scope: 'vehicle_device_data' },
  { key: 'climate_state_timestamp', label: 'Climate state timestamp', group: 'climate_state', path: 'climate_state.timestamp', type: 'number', unit: 'ms', scope: 'vehicle_device_data' },
  { key: 'odometer', label: 'Odometer', group: 'vehicle_state', path: 'vehicle_state.odometer', type: 'number', unit: 'mi', scope: 'vehicle_device_data' },
  { key: 'locked', label: 'Locked', group: 'vehicle_state', path: 'vehicle_state.locked', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'sentry_mode', label: 'Sentry Mode active', group: 'vehicle_state', path: 'vehicle_state.sentry_mode', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'sentry_mode_available', label: 'Sentry Mode available', group: 'vehicle_state', path: 'vehicle_state.sentry_mode_available', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'is_user_present', label: 'User present', group: 'vehicle_state', path: 'vehicle_state.is_user_present', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'vehicle_name', label: 'Vehicle name', group: 'vehicle_state', path: 'vehicle_state.vehicle_name', type: 'string', scope: 'vehicle_device_data' },
  { key: 'car_version', label: 'Software version', group: 'vehicle_state', path: 'vehicle_state.car_version', type: 'string', scope: 'vehicle_device_data' },
  { key: 'df', label: 'Door open: driver front', group: 'vehicle_state', path: 'vehicle_state.df', type: 'number', scope: 'vehicle_device_data' },
  { key: 'dr', label: 'Door open: driver rear', group: 'vehicle_state', path: 'vehicle_state.dr', type: 'number', scope: 'vehicle_device_data' },
  { key: 'pf', label: 'Door open: passenger front', group: 'vehicle_state', path: 'vehicle_state.pf', type: 'number', scope: 'vehicle_device_data' },
  { key: 'pr', label: 'Door open: passenger rear', group: 'vehicle_state', path: 'vehicle_state.pr', type: 'number', scope: 'vehicle_device_data' },
  { key: 'ft', label: 'Front trunk (frunk) open', group: 'vehicle_state', path: 'vehicle_state.ft', type: 'number', scope: 'vehicle_device_data' },
  { key: 'rt', label: 'Rear trunk open', group: 'vehicle_state', path: 'vehicle_state.rt', type: 'number', scope: 'vehicle_device_data' },
  { key: 'fd_window', label: 'Window: front driver', group: 'vehicle_state', path: 'vehicle_state.fd_window', type: 'number', scope: 'vehicle_device_data' },
  { key: 'fp_window', label: 'Window: front passenger', group: 'vehicle_state', path: 'vehicle_state.fp_window', type: 'number', scope: 'vehicle_device_data' },
  { key: 'rd_window', label: 'Window: rear driver', group: 'vehicle_state', path: 'vehicle_state.rd_window', type: 'number', scope: 'vehicle_device_data' },
  { key: 'rp_window', label: 'Window: rear passenger', group: 'vehicle_state', path: 'vehicle_state.rp_window', type: 'number', scope: 'vehicle_device_data' },
  { key: 'sun_roof_percent_open', label: 'Sun roof percent open', group: 'vehicle_state', path: 'vehicle_state.sun_roof_percent_open', type: 'number', unit: '%', scope: 'vehicle_device_data' },
  { key: 'sun_roof_state', label: 'Sun roof state', group: 'vehicle_state', path: 'vehicle_state.sun_roof_state', type: 'string', scope: 'vehicle_device_data' },
  { key: 'tpms_pressure_fl', label: 'Tire pressure front left', group: 'vehicle_state', path: 'vehicle_state.tpms_pressure_fl', type: 'number', unit: 'bar', scope: 'vehicle_device_data' },
  { key: 'tpms_pressure_fr', label: 'Tire pressure front right', group: 'vehicle_state', path: 'vehicle_state.tpms_pressure_fr', type: 'number', unit: 'bar', scope: 'vehicle_device_data' },
  { key: 'tpms_pressure_rl', label: 'Tire pressure rear left', group: 'vehicle_state', path: 'vehicle_state.tpms_pressure_rl', type: 'number', unit: 'bar', scope: 'vehicle_device_data' },
  { key: 'tpms_pressure_rr', label: 'Tire pressure rear right', group: 'vehicle_state', path: 'vehicle_state.tpms_pressure_rr', type: 'number', unit: 'bar', scope: 'vehicle_device_data' },
  { key: 'tpms_soft_warning_fl', label: 'Tire low-pressure warning front left', group: 'vehicle_state', path: 'vehicle_state.tpms_soft_warning_fl', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'tpms_soft_warning_fr', label: 'Tire low-pressure warning front right', group: 'vehicle_state', path: 'vehicle_state.tpms_soft_warning_fr', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'tpms_soft_warning_rl', label: 'Tire low-pressure warning rear left', group: 'vehicle_state', path: 'vehicle_state.tpms_soft_warning_rl', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'tpms_soft_warning_rr', label: 'Tire low-pressure warning rear right', group: 'vehicle_state', path: 'vehicle_state.tpms_soft_warning_rr', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'tpms_hard_warning_fl', label: 'Tire critical-pressure warning front left', group: 'vehicle_state', path: 'vehicle_state.tpms_hard_warning_fl', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'tpms_hard_warning_fr', label: 'Tire critical-pressure warning front right', group: 'vehicle_state', path: 'vehicle_state.tpms_hard_warning_fr', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'tpms_hard_warning_rl', label: 'Tire critical-pressure warning rear left', group: 'vehicle_state', path: 'vehicle_state.tpms_hard_warning_rl', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'tpms_hard_warning_rr', label: 'Tire critical-pressure warning rear right', group: 'vehicle_state', path: 'vehicle_state.tpms_hard_warning_rr', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'tpms_rcp_front_value', label: 'Tire recommended pressure front', group: 'vehicle_state', path: 'vehicle_state.tpms_rcp_front_value', type: 'number', unit: 'bar', scope: 'vehicle_device_data' },
  { key: 'tpms_rcp_rear_value', label: 'Tire recommended pressure rear', group: 'vehicle_state', path: 'vehicle_state.tpms_rcp_rear_value', type: 'number', unit: 'bar', scope: 'vehicle_device_data' },
  { key: 'software_update', label: 'Software update', group: 'vehicle_state', path: 'vehicle_state.software_update', type: 'object', scope: 'vehicle_device_data' },
  { key: 'speed_limit_mode', label: 'Speed limit mode', group: 'vehicle_state', path: 'vehicle_state.speed_limit_mode', type: 'object', scope: 'vehicle_device_data' },
  { key: 'media_info', label: 'Media info (now playing)', group: 'vehicle_state', path: 'vehicle_state.media_info', type: 'object', scope: 'vehicle_device_data' },
  { key: 'valet_mode', label: 'Valet Mode active', group: 'vehicle_state', path: 'vehicle_state.valet_mode', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'remote_start', label: 'Remote start active', group: 'vehicle_state', path: 'vehicle_state.remote_start', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'homelink_device_count', label: 'HomeLink device count', group: 'vehicle_state', path: 'vehicle_state.homelink_device_count', type: 'number', scope: 'vehicle_device_data' },
  { key: 'homelink_nearby', label: 'HomeLink nearby', group: 'vehicle_state', path: 'vehicle_state.homelink_nearby', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'dashcam_state', label: 'Dashcam state', group: 'vehicle_state', path: 'vehicle_state.dashcam_state', type: 'string', scope: 'vehicle_device_data' },
  { key: 'service_mode', label: 'Service Mode active', group: 'vehicle_state', path: 'vehicle_state.service_mode', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'vehicle_state_timestamp', label: 'Vehicle state timestamp', group: 'vehicle_state', path: 'vehicle_state.timestamp', type: 'number', unit: 'ms', scope: 'vehicle_device_data' },
  { key: 'shift_state', label: 'Shift state', group: 'drive_state', path: 'drive_state.shift_state', type: 'string', scope: 'vehicle_device_data' },
  { key: 'speed', label: 'Speed', group: 'drive_state', path: 'drive_state.speed', type: 'number', unit: 'mph', scope: 'vehicle_device_data' },
  { key: 'power', label: 'Drive power', group: 'drive_state', path: 'drive_state.power', type: 'number', unit: 'kW', scope: 'vehicle_device_data' },
  { key: 'latitude', label: 'Latitude', group: 'drive_state', path: 'drive_state.latitude', type: 'number', unit: 'deg', scope: 'vehicle_location' },
  { key: 'longitude', label: 'Longitude', group: 'drive_state', path: 'drive_state.longitude', type: 'number', unit: 'deg', scope: 'vehicle_location' },
  { key: 'heading', label: 'Heading', group: 'drive_state', path: 'drive_state.heading', type: 'number', unit: 'deg', scope: 'vehicle_location' },
  { key: 'gps_as_of', label: 'GPS fix time', group: 'drive_state', path: 'drive_state.gps_as_of', type: 'number', unit: 's', scope: 'vehicle_location' },
  { key: 'active_route_destination', label: 'Active route destination', group: 'drive_state', path: 'drive_state.active_route_destination', type: 'string', scope: 'vehicle_location' },
  { key: 'active_route_latitude', label: 'Active route destination latitude', group: 'drive_state', path: 'drive_state.active_route_latitude', type: 'number', unit: 'deg', scope: 'vehicle_location' },
  { key: 'active_route_longitude', label: 'Active route destination longitude', group: 'drive_state', path: 'drive_state.active_route_longitude', type: 'number', unit: 'deg', scope: 'vehicle_location' },
  { key: 'active_route_miles_to_arrival', label: 'Active route miles to arrival', group: 'drive_state', path: 'drive_state.active_route_miles_to_arrival', type: 'number', unit: 'mi', scope: 'vehicle_device_data' },
  { key: 'active_route_minutes_to_arrival', label: 'Active route minutes to arrival', group: 'drive_state', path: 'drive_state.active_route_minutes_to_arrival', type: 'number', unit: 'min', scope: 'vehicle_device_data' },
  { key: 'active_route_traffic_minutes_delay', label: 'Active route traffic delay', group: 'drive_state', path: 'drive_state.active_route_traffic_minutes_delay', type: 'number', unit: 'min', scope: 'vehicle_device_data' },
  { key: 'active_route_energy_at_arrival', label: 'Active route SoC at arrival', group: 'drive_state', path: 'drive_state.active_route_energy_at_arrival', type: 'number', unit: '%', scope: 'vehicle_device_data' },
  { key: 'drive_state_timestamp', label: 'Drive state timestamp', group: 'drive_state', path: 'drive_state.timestamp', type: 'number', unit: 'ms', scope: 'vehicle_device_data' },
  { key: 'gui_distance_units', label: 'Distance units', group: 'gui_settings', path: 'gui_settings.gui_distance_units', type: 'string', scope: 'vehicle_device_data' },
  { key: 'gui_temperature_units', label: 'Temperature units', group: 'gui_settings', path: 'gui_settings.gui_temperature_units', type: 'string', scope: 'vehicle_device_data' },
  { key: 'gui_charge_rate_units', label: 'Charge rate units', group: 'gui_settings', path: 'gui_settings.gui_charge_rate_units', type: 'string', scope: 'vehicle_device_data' },
  { key: 'gui_range_display', label: 'Range display mode', group: 'gui_settings', path: 'gui_settings.gui_range_display', type: 'string', scope: 'vehicle_device_data' },
  { key: 'gui_24_hour_time', label: '24-hour time', group: 'gui_settings', path: 'gui_settings.gui_24_hour_time', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'gui_settings_timestamp', label: 'GUI settings timestamp', group: 'gui_settings', path: 'gui_settings.timestamp', type: 'number', unit: 'ms', scope: 'vehicle_device_data' },
  { key: 'car_type', label: 'Car type', group: 'vehicle_config', path: 'vehicle_config.car_type', type: 'string', scope: 'vehicle_device_data' },
  { key: 'trim_badging', label: 'Trim badging', group: 'vehicle_config', path: 'vehicle_config.trim_badging', type: 'string', scope: 'vehicle_device_data' },
  { key: 'exterior_color', label: 'Exterior color', group: 'vehicle_config', path: 'vehicle_config.exterior_color', type: 'string', scope: 'vehicle_device_data' },
  { key: 'roof_color', label: 'Roof color', group: 'vehicle_config', path: 'vehicle_config.roof_color', type: 'string', scope: 'vehicle_device_data' },
  { key: 'wheel_type', label: 'Wheel type', group: 'vehicle_config', path: 'vehicle_config.wheel_type', type: 'string', scope: 'vehicle_device_data' },
  { key: 'interior_trim_type', label: 'Interior trim type', group: 'vehicle_config', path: 'vehicle_config.interior_trim_type', type: 'string', scope: 'vehicle_device_data' },
  { key: 'third_row_seats', label: 'Third row seats', group: 'vehicle_config', path: 'vehicle_config.third_row_seats', type: 'string', scope: 'vehicle_device_data' },
  { key: 'rear_seat_heaters', label: 'Rear seat heaters present', group: 'vehicle_config', path: 'vehicle_config.rear_seat_heaters', type: 'number', scope: 'vehicle_device_data' },
  { key: 'charge_port_type', label: 'Charge port type', group: 'vehicle_config', path: 'vehicle_config.charge_port_type', type: 'string', scope: 'vehicle_device_data' },
  { key: 'motorized_charge_port', label: 'Motorized charge port', group: 'vehicle_config', path: 'vehicle_config.motorized_charge_port', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'can_actuate_trunks', label: 'Can actuate trunks', group: 'vehicle_config', path: 'vehicle_config.can_actuate_trunks', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'can_accept_navigation_requests', label: 'Accepts navigation requests', group: 'vehicle_config', path: 'vehicle_config.can_accept_navigation_requests', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'has_air_suspension', label: 'Has air suspension', group: 'vehicle_config', path: 'vehicle_config.has_air_suspension', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'has_seat_cooling', label: 'Has seat cooling', group: 'vehicle_config', path: 'vehicle_config.has_seat_cooling', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'plg', label: 'Power liftgate equipped', group: 'vehicle_config', path: 'vehicle_config.plg', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'default_charge_to_max', label: 'Default charge to max', group: 'vehicle_config', path: 'vehicle_config.default_charge_to_max', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'eu_vehicle', label: 'EU-market vehicle', group: 'vehicle_config', path: 'vehicle_config.eu_vehicle', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'rhd', label: 'Right-hand drive', group: 'vehicle_config', path: 'vehicle_config.rhd', type: 'boolean', scope: 'vehicle_device_data' },
  { key: 'utc_offset', label: 'Vehicle UTC offset', group: 'vehicle_config', path: 'vehicle_config.utc_offset', type: 'number', unit: 's', scope: 'vehicle_device_data' },
  { key: 'vehicle_config_timestamp', label: 'Vehicle config timestamp', group: 'vehicle_config', path: 'vehicle_config.timestamp', type: 'number', unit: 'ms', scope: 'vehicle_device_data' },
];

const byKey = new Map(METRICS.map(m => [m.key, m]));
function getMetric(key) { return byKey.get(key); }
function metricKeys() { return METRICS.map(m => m.key); }
function metricsByGroup() {
  const out = {};
  for (const m of METRICS) (out[m.group] ||= []).push(m);
  return out;
}

module.exports = { METRICS, getMetric, metricKeys, metricsByGroup };
